add sample with motor
ev3go/brickpi pull request #14
Opened 2021-02-01 16:24 UTC by maniSbindra

Fixes #13 . This PR adds motor sample which works with both nxt and ev3 large motors

2021-02-01 20:53 UTC, kortschak reviewed
Thanks.

It seems to me that this could be more concisely and simply expressed as
```
	m, err := ev3dev.TachoMotorFor("", "lego-nxt-motor")
	if err != nil {
		log.Fatalf("failed to find lego-nxt-motor motor port: %v", err)
	}
	err = m.SetSpeedSetpoint(500).SetPositionSetpoint(180).SetStopAction("hold").Command("run-to-rel-pos").Err()
	if err != nil {
		log.Fatalf("error during motor operation: %v", err)
	}
```

Is there more information that you are trying to get across in the example?

2021-02-02 16:42 UTC, maniSbindra commented
Thanks @kortschak, I have simplified the sample as per your suggestion.

2021-02-02 20:47 UTC, kortschak commented on examples/motor/motor.go
> +	m, err := ev3dev.TachoMotorFor("serial0-0:MA", "lego-nxt-motor")
This is not semantically the same the the equivalent line in my suggestion. This specifically requires that the lego-nxt-motor be on motor port A. The code I suggested will find the first available lego-nxt-motor (which will be on port 1 if there is a motor attached to that port).

Given that this is an example to help users, I'm wondering what information it is that you are wanting to get across to the reader. If it's how to attach a single motor to the device, the code I provided is the best way since it's port agnostic. If you are showing how to find the port address, then a documented constant `const MotorPrefix = "serial0-0:M"` (or `DeviceNodePrefix = "serial0-0:"`) with a link to the ev3dev motor device driver [documentation](http://docs.ev3dev.org/projects/lego-linux-drivers/en/ev3dev-stretch/brickpi.html#output-ports) would be most appropriate.

Can you tell me what information you are trying to convey? Also, have you tested this on a device? The docs say the motor ports have a numeric identifier, not an alpha.

2021-02-02 20:47 UTC, kortschak commented on examples/motor/motor.go
> +
Please delete this blank line, and the trailing blank in the main block.

2021-02-02 20:47 UTC, kortschak commented on examples/motor/motor.go
> +package main
Please add ev3dev copyright header.

2021-02-03 02:30 UTC, maniSbindra commented on examples/motor/motor.go
> +package main
Hi @kortschak. A few points:

- I have tested the code on a Brickpi with both nxt and ev3 large motors
- When I was initially wrote the code I could not find what the port and driver configurations should be for the motors, and had to look at the ev3dev python source code for that.
- The intent of this example as mentioned in the linked issue was for developers to easily find out the driver and the port configuration for motors when using ev3dev go with Brickpi
- If you look at the initial commit of this PR, I did have the **port prefix** defined in the initial commit with **relevant comments** in the PR (initial commit code section below), but I modified based on what I thought was your review feedback. 
  
   ``` // degrees to rotate motor by
	rotateDegree := 180

	// Motor Port can be A, B, C or D
	motorPort := "D"

	motorStopAction := "hold" // can be brake, hold etc

	// Motor driver .This value works for both nxt and ev3 large motor
	motorDriver := "lego-nxt-motor"

	// motor Port String format
	motorPortStringPrefix := "serial0-0:M" ```

- I am happy to discuss this further, and also happy to close this PR, as folks not able to find the driver values for ev3 and nxt motors on ev3dev/brickpi-go will run into this issue and get the relevant details.

Thanks,
Mani

2021-02-03 02:51 UTC, kortschak commented on examples/motor/motor.go
> +package main
Thanks for that.

Did the code without the explicit port address not work?

I think it's worth either having the example or improving the documentation in the package. I'd like to take a understand the behaviour on the device before we move ahead (the disparity between the behaviour you are seeing and the ev3dev BrickPi documentation is troubling), but I have only EV3 motors (no NXT).

2021-02-03 03:01 UTC, maniSbindra commented on examples/motor/motor.go
> +package main
Hi @kortschak, some additional information:
*  I am using BrickPi (not BrickPlus or Brickpi3).
*  I will be using multiple nxt motors for my use case, for which I need to rotate an exact number of degrees
*  I tried to use  **ev3dev.TachoMotorFor**("serial0-0:MA", "lego-nxt-motor") operation, for multiple motors which required me to specify exact motor port, It will be great if you can point me to how you want me to test without explicit port address and I will share the results here.

Thanks

2021-02-03 03:49 UTC, kortschak commented on examples/motor/motor.go
> +package main
I forgot how much I dislike BrickPi. This may take longer than I thought.

2021-02-03 06:59 UTC, kortschak commented on examples/motor/motor.go
> +package main
OK, I have this clear enough for me. What I think we probably want is a combination of two things

1. constants or functions in the package to make the port for a given motor or sensor easily available
2. the example here, probably a combination of yours and my changes (I left out comments for brevity, they should certainly be retained).

I was wrong about the auto-finding of devices by driver; this only works on EV3 (maybe FatCat?) and not no BrickPi because of its design limitations. It will always find port A. You should be able to use code like in [this example](https://github.com/ev3go/ev3dev/blob/master/examples/findafter/findafter.go).

2021-02-04 13:25 UTC, maniSbindra commented on examples/motor/motor.go
> +package main
Hi @kortschak I have modified the example as per my understanding, please do let me know of the further changes needed. I have tested this sample with both nxt and ev3 motors. Thanks

2021-02-04 22:45 UTC, kortschak requested changes

2021-02-04 22:45 UTC, kortschak commented on examples/motor/motor.go
> +// Copyright ©2016 The ev3go Authors. All rights reserved.
2021?

2021-02-04 22:45 UTC, kortschak commented on examples/motor/motor.go
> +	motorPortString := fmt.Sprintf("%s%s", motorPortStringPrefix, motorPort)
```
const (
	// motorDriver is the default BrickPi motorDriver. For details, see
	// http://docs.ev3dev.org/projects/lego-linux-drivers/en/ev3dev-stretch/brickpi.html#output-ports
	motorDriver = "lego-nxt-motor"

	// motorPortPrefix is the prefix for BrickPi output port addresses. The
	// prefix must have the specific port appended. Posts can be  A, B, C or D,
	// corresponding to the BrickPi output ports MA, MB, MC and MD.
	motorPortPrefix = "serial0-0:M"
)
```

2021-02-04 22:45 UTC, kortschak commented on examples/motor/motor.go
> +	m, err := ev3dev.TachoMotorFor(motorPortString, motorDriver)
```
m, err := ev3dev.TachoMotorFor(motorPortPrefix+"A", motorDriver)
```

2021-02-04 22:46 UTC, kortschak commented
Can you also add yourself (and employer if relevant) to AUTHORS and CONTRIBUTORS.

2021-02-07 17:23 UTC, maniSbindra commented on examples/motor/motor.go
> +// Copyright ©2016 The ev3go Authors. All rights reserved.
Done.

2021-02-07 17:24 UTC, maniSbindra commented on examples/motor/motor.go
> +	m, err := ev3dev.TachoMotorFor(motorPortString, motorDriver)
Done.

2021-02-08 00:00 UTC, kortschak reviewed
Thank you. Three minor nits and then it's ready to merge.

2021-02-08 06:34 UTC, maniSbindra commented
Thanks @kortschak . Done.

2021-02-08 09:27 UTC, kortschak approved these changes
Thanks

2021-02-08 09:28 UTC, merged